# reference: https://github.com/f1sty/f1sty.github.io/blob/main/_config.yml
#theme: no-style-please
exclude: [7thh9p/node_modules]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: minima

title: Kien's stuffs
email: vutrankien.vn@gmail.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Blog about things I'm interested. Programming, Clean code, OOP, 
github_username: kentvu
twitter_username: vutrankien

minima:
  skin: solarized

header_pages:
  - about.md
  - index.html
